import {
  Accessibility, AlertTriangle, Apple, Armchair, ArrowDown, ArrowDownLeft, ArrowDownRight, ArrowLeft,
  ArrowRight, ArrowUp, ArrowUpLeft, ArrowUpRight, Baby, Ban, Bath, BedDouble, Bell, Bike, Binoculars,
  Bird, BookOpen, Brush, Bug, Building2, Bus, Calendar, Camera, Car, Castle, Cat, ChevronsUp, Church,
  Clapperboard, Clock, Coffee, Compass, CookingPot, CornerUpLeft, CornerUpRight, Cross, Crown, CupSoda,
  Dice5, Dog, DoorClosed, DoorOpen, Drama, Droplet, Eye, Factory, Film, FireExtinguisher, Fish, Flag,
  Flame, FlaskConical, Flower2, Footprints, Fuel, Gamepad2, Gem, Ghost, Gift, GraduationCap, Guitar,
  Hammer, Headphones, Heart, HeartPulse, Home, Hospital, Hotel, KeyRound, Lamp, Landmark, Library,
  Lightbulb, Lock, LogIn, LogOut, Map, MapPin, Medal, Mic, Microwave, Milestone, Monitor, Moon,
  Mountain, Music, Navigation, Newspaper, Package, Palette, PawPrint, PersonStanding, Phone, Piano,
  Pizza, Plane, Printer, Shield, Puzzle, Rabbit, Recycle, Refrigerator, Rocket, Route, School, Ship, ShoppingCart,
  ShowerHead, Signpost, Siren, Snowflake, Sofa, Sparkles, Star, Stethoscope, Store, Sun, Telescope,
  Tent, Ticket, TrainFront, Trash2, TreePine, Trees, Trophy, Turtle, Tv, Umbrella, User, Users,
  Utensils, UtensilsCrossed, Warehouse, WashingMachine, Waves, Wifi, Wine, Wrench, Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Catálogo de iconos elegibles para un hotspot.
 *
 * El nombre en kebab-case es el que viaja en tour.json (`style.icon.name`) y
 * el que el visor sabe dibujar: cada entrada de aquí tiene su gemela en el
 * registro de `packages/viewer/src/hotspots/icons.ts`. Las palabras clave son
 * para el buscador del selector, en español y en inglés.
 */
export interface HotspotIconOption {
  name: string;
  Icon: LucideIcon;
  keywords: string[];
}

export const ICON_CATALOG: HotspotIconOption[] = [
  // Flechas y pasos
  { name: "arrow-up", Icon: ArrowUp, keywords: ["flecha", "arriba", "adelante", "up"] },
  { name: "arrow-down", Icon: ArrowDown, keywords: ["flecha", "abajo", "down"] },
  { name: "arrow-left", Icon: ArrowLeft, keywords: ["flecha", "izquierda", "left"] },
  { name: "arrow-right", Icon: ArrowRight, keywords: ["flecha", "derecha", "right"] },
  { name: "arrow-up-right", Icon: ArrowUpRight, keywords: ["flecha", "diagonal"] },
  { name: "arrow-up-left", Icon: ArrowUpLeft, keywords: ["flecha", "diagonal"] },
  { name: "arrow-down-right", Icon: ArrowDownRight, keywords: ["flecha", "diagonal"] },
  { name: "arrow-down-left", Icon: ArrowDownLeft, keywords: ["flecha", "diagonal"] },
  { name: "corner-up-right", Icon: CornerUpRight, keywords: ["giro", "esquina", "doblar"] },
  { name: "corner-up-left", Icon: CornerUpLeft, keywords: ["giro", "esquina", "doblar"] },
  { name: "chevrons-up", Icon: ChevronsUp, keywords: ["subir", "escaleras", "planta", "stairs"] },
  { name: "footprints", Icon: Footprints, keywords: ["pasos", "huellas", "andar", "walk"] },
  { name: "door-open", Icon: DoorOpen, keywords: ["puerta", "entrar", "salida", "door"] },
  { name: "door-closed", Icon: DoorClosed, keywords: ["puerta", "cerrada", "privado"] },
  { name: "log-in", Icon: LogIn, keywords: ["entrada", "entrar"] },
  { name: "log-out", Icon: LogOut, keywords: ["salida", "salir", "emergencia"] },
  { name: "compass", Icon: Compass, keywords: ["brujula", "norte", "orientacion"] },
  { name: "navigation", Icon: Navigation, keywords: ["gps", "rumbo", "puntero"] },
  { name: "route", Icon: Route, keywords: ["ruta", "camino", "recorrido"] },
  { name: "signpost", Icon: Signpost, keywords: ["senal", "cartel", "direccion", "poste"] },
  { name: "milestone", Icon: Milestone, keywords: ["hito", "senal", "kilometro"] },
  { name: "map", Icon: Map, keywords: ["mapa", "plano"] },
  { name: "map-pin", Icon: MapPin, keywords: ["lugar", "marcador", "sitio", "pin"] },
  // Edificios y lugares
  { name: "home", Icon: Home, keywords: ["casa", "inicio", "hogar"] },
  { name: "building-2", Icon: Building2, keywords: ["edificio", "oficina", "bloque"] },
  { name: "hotel", Icon: Hotel, keywords: ["hotel", "alojamiento"] },
  { name: "landmark", Icon: Landmark, keywords: ["monumento", "museo", "banco", "patrimonio"] },
  { name: "church", Icon: Church, keywords: ["iglesia", "ermita", "capilla", "templo"] },
  { name: "castle", Icon: Castle, keywords: ["castillo", "fortaleza", "muralla"] },
  { name: "warehouse", Icon: Warehouse, keywords: ["nave", "almacen", "hangar"] },
  { name: "factory", Icon: Factory, keywords: ["fabrica", "industria", "taller"] },
  { name: "store", Icon: Store, keywords: ["tienda", "comercio", "kiosco"] },
  { name: "school", Icon: School, keywords: ["colegio", "escuela", "instituto"] },
  { name: "hospital", Icon: Hospital, keywords: ["hospital", "clinica", "sanidad"] },
  { name: "tent", Icon: Tent, keywords: ["tienda de campana", "camping", "carpa"] },
  { name: "graduation-cap", Icon: GraduationCap, keywords: ["universidad", "aula", "birrete"] },
  { name: "book-open", Icon: BookOpen, keywords: ["libro", "lectura", "biblioteca"] },
  { name: "library", Icon: Library, keywords: ["biblioteca", "estanteria", "archivo"] },
  { name: "flask-conical", Icon: FlaskConical, keywords: ["laboratorio", "quimica", "ciencia"] },
  // Naturaleza y exterior
  { name: "trees", Icon: Trees, keywords: ["arboles", "bosque", "parque", "jardin"] },
  { name: "tree-pine", Icon: TreePine, keywords: ["pino", "arbol", "monte"] },
  { name: "flower-2", Icon: Flower2, keywords: ["flor", "jardin", "primavera"] },
  { name: "mountain", Icon: Mountain, keywords: ["montana", "cumbre", "senderismo"] },
  { name: "waves", Icon: Waves, keywords: ["mar", "playa", "olas", "piscina"] },
  { name: "sun", Icon: Sun, keywords: ["sol", "terraza", "exterior", "dia"] },
  { name: "moon", Icon: Moon, keywords: ["luna", "noche"] },
  { name: "umbrella", Icon: Umbrella, keywords: ["sombrilla", "paraguas", "playa"] },
  { name: "snowflake", Icon: Snowflake, keywords: ["nieve", "frio", "invierno", "hielo"] },
  { name: "droplet", Icon: Droplet, keywords: ["agua", "gota", "fuente"] },
  { name: "flame", Icon: Flame, keywords: ["fuego", "llama", "chimenea", "caldera"] },
  { name: "zap", Icon: Zap, keywords: ["rayo", "electricidad", "energia", "cuadro"] },
  // Transporte
  { name: "car", Icon: Car, keywords: ["coche", "aparcamiento", "parking", "garaje"] },
  { name: "bus", Icon: Bus, keywords: ["autobus", "guagua", "parada"] },
  { name: "bike", Icon: Bike, keywords: ["bicicleta", "bici", "carril"] },
  { name: "train-front", Icon: TrainFront, keywords: ["tren", "tranvia", "metro", "estacion"] },
  { name: "plane", Icon: Plane, keywords: ["avion", "aeropuerto", "vuelo"] },
  { name: "ship", Icon: Ship, keywords: ["barco", "puerto", "ferry", "muelle"] },
  { name: "fuel", Icon: Fuel, keywords: ["gasolinera", "combustible", "surtidor"] },
  // Salas y objetos de casa
  { name: "bed-double", Icon: BedDouble, keywords: ["dormitorio", "cama", "habitacion"] },
  { name: "bath", Icon: Bath, keywords: ["bano", "banera", "aseo"] },
  { name: "shower-head", Icon: ShowerHead, keywords: ["ducha", "bano"] },
  { name: "sofa", Icon: Sofa, keywords: ["salon", "sofa", "estar"] },
  { name: "armchair", Icon: Armchair, keywords: ["sillon", "butaca", "sala"] },
  { name: "lamp", Icon: Lamp, keywords: ["lampara", "luz", "iluminacion"] },
  { name: "utensils", Icon: Utensils, keywords: ["cocina", "comedor", "cubiertos"] },
  { name: "utensils-crossed", Icon: UtensilsCrossed, keywords: ["restaurante", "comida", "menu"] },
  { name: "cooking-pot", Icon: CookingPot, keywords: ["olla", "cocina", "guiso"] },
  { name: "refrigerator", Icon: Refrigerator, keywords: ["nevera", "frigorifico", "cocina"] },
  { name: "microwave", Icon: Microwave, keywords: ["microondas", "horno", "cocina"] },
  { name: "washing-machine", Icon: WashingMachine, keywords: ["lavadora", "lavadero", "colada"] },
  { name: "wine", Icon: Wine, keywords: ["vino", "copa", "bodega", "bar"] },
  { name: "coffee", Icon: Coffee, keywords: ["cafe", "cafeteria", "taza", "descanso"] },
  { name: "cup-soda", Icon: CupSoda, keywords: ["refresco", "bebida", "bar"] },
  { name: "pizza", Icon: Pizza, keywords: ["pizza", "comida", "restaurante"] },
  { name: "apple", Icon: Apple, keywords: ["fruta", "manzana", "mercado", "saludable"] },
  // Servicios y objetos
  { name: "shopping-cart", Icon: ShoppingCart, keywords: ["compra", "carro", "supermercado"] },
  { name: "gift", Icon: Gift, keywords: ["regalo", "sorpresa", "tienda"] },
  { name: "ticket", Icon: Ticket, keywords: ["entrada", "taquilla", "billete"] },
  { name: "key-round", Icon: KeyRound, keywords: ["llave", "recepcion", "acceso"] },
  { name: "lock", Icon: Lock, keywords: ["candado", "cerrado", "privado", "seguridad"] },
  { name: "bell", Icon: Bell, keywords: ["campana", "timbre", "aviso", "recepcion"] },
  { name: "clock", Icon: Clock, keywords: ["reloj", "horario", "hora"] },
  { name: "calendar", Icon: Calendar, keywords: ["calendario", "fecha", "evento", "agenda"] },
  { name: "wrench", Icon: Wrench, keywords: ["llave inglesa", "mantenimiento", "taller"] },
  { name: "hammer", Icon: Hammer, keywords: ["martillo", "obra", "herramienta"] },
  { name: "lightbulb", Icon: Lightbulb, keywords: ["idea", "bombilla", "luz", "consejo"] },
  { name: "trash-2", Icon: Trash2, keywords: ["papelera", "basura", "residuos"] },
  { name: "recycle", Icon: Recycle, keywords: ["reciclaje", "contenedor", "verde"] },
  { name: "package", Icon: Package, keywords: ["paquete", "caja", "almacen", "envio"] },
  { name: "printer", Icon: Printer, keywords: ["impresora", "reprografia", "oficina"] },
  { name: "wifi", Icon: Wifi, keywords: ["wifi", "red", "internet", "conexion"] },
  { name: "phone", Icon: Phone, keywords: ["telefono", "llamada", "contacto"] },
  { name: "monitor", Icon: Monitor, keywords: ["pantalla", "ordenador", "informatica"] },
  { name: "tv", Icon: Tv, keywords: ["television", "pantalla", "proyeccion"] },
  { name: "gamepad-2", Icon: Gamepad2, keywords: ["juego", "mando", "videojuegos", "ocio"] },
  // Cultura y medios
  { name: "music", Icon: Music, keywords: ["musica", "nota", "concierto"] },
  { name: "mic", Icon: Mic, keywords: ["microfono", "escenario", "audio", "karaoke"] },
  { name: "headphones", Icon: Headphones, keywords: ["auriculares", "audioguia", "escucha"] },
  { name: "guitar", Icon: Guitar, keywords: ["guitarra", "musica", "instrumento"] },
  { name: "piano", Icon: Piano, keywords: ["piano", "musica", "teclado"] },
  { name: "palette", Icon: Palette, keywords: ["arte", "pintura", "paleta", "museo"] },
  { name: "brush", Icon: Brush, keywords: ["pincel", "pintura", "taller de arte"] },
  { name: "drama", Icon: Drama, keywords: ["teatro", "mascaras", "escena", "comedia"] },
  { name: "newspaper", Icon: Newspaper, keywords: ["periodico", "prensa", "noticias"] },
  { name: "camera", Icon: Camera, keywords: ["camara", "foto", "mirador"] },
  { name: "film", Icon: Film, keywords: ["cine", "pelicula", "fotograma"] },
  { name: "clapperboard", Icon: Clapperboard, keywords: ["claqueta", "rodaje", "cine"] },
  { name: "telescope", Icon: Telescope, keywords: ["telescopio", "observatorio", "estrellas"] },
  { name: "binoculars", Icon: Binoculars, keywords: ["prismaticos", "mirador", "vistas"] },
  { name: "eye", Icon: Eye, keywords: ["ojo", "mirar", "vista", "observar"] },
  // Personas, salud y seguridad
  { name: "users", Icon: Users, keywords: ["personas", "grupo", "reunion", "publico"] },
  { name: "user", Icon: User, keywords: ["persona", "perfil", "individual"] },
  { name: "person-standing", Icon: PersonStanding, keywords: ["persona", "figura", "punto de encuentro"] },
  { name: "accessibility", Icon: Accessibility, keywords: ["accesibilidad", "silla de ruedas", "adaptado"] },
  { name: "baby", Icon: Baby, keywords: ["bebe", "infantil", "cambiador", "guarderia"] },
  { name: "heart", Icon: Heart, keywords: ["corazon", "favorito", "amor"] },
  { name: "heart-pulse", Icon: HeartPulse, keywords: ["salud", "pulso", "urgencias", "desfibrilador"] },
  { name: "stethoscope", Icon: Stethoscope, keywords: ["medico", "consulta", "enfermeria"] },
  { name: "cross", Icon: Cross, keywords: ["cruz", "botiquin", "primeros auxilios"] },
  { name: "shield", Icon: Shield, keywords: ["seguridad", "proteccion", "vigilancia"] },
  { name: "siren", Icon: Siren, keywords: ["alarma", "emergencia", "sirena"] },
  { name: "fire-extinguisher", Icon: FireExtinguisher, keywords: ["extintor", "incendio", "emergencia"] },
  { name: "alert-triangle", Icon: AlertTriangle, keywords: ["aviso", "peligro", "atencion", "cuidado"] },
  { name: "ban", Icon: Ban, keywords: ["prohibido", "no pasar", "restringido"] },
  // Animales
  { name: "dog", Icon: Dog, keywords: ["perro", "mascota", "animal"] },
  { name: "cat", Icon: Cat, keywords: ["gato", "mascota", "animal"] },
  { name: "bird", Icon: Bird, keywords: ["pajaro", "ave", "ornitologia"] },
  { name: "fish", Icon: Fish, keywords: ["pez", "acuario", "pesca"] },
  { name: "paw-print", Icon: PawPrint, keywords: ["huella", "mascotas", "animales", "zoo"] },
  { name: "bug", Icon: Bug, keywords: ["insecto", "bicho", "entomologia"] },
  { name: "rabbit", Icon: Rabbit, keywords: ["conejo", "granja", "animal"] },
  { name: "turtle", Icon: Turtle, keywords: ["tortuga", "lento", "animal"] },
  // Celebración y varios
  { name: "trophy", Icon: Trophy, keywords: ["trofeo", "premio", "deporte", "logro"] },
  { name: "medal", Icon: Medal, keywords: ["medalla", "premio", "podio"] },
  { name: "crown", Icon: Crown, keywords: ["corona", "rey", "historia"] },
  { name: "rocket", Icon: Rocket, keywords: ["cohete", "espacio", "lanzamiento"] },
  { name: "sparkles", Icon: Sparkles, keywords: ["brillos", "magia", "nuevo", "destacado"] },
  { name: "star", Icon: Star, keywords: ["estrella", "favorito", "destacado"] },
  { name: "flag", Icon: Flag, keywords: ["bandera", "meta", "punto"] },
  { name: "gem", Icon: Gem, keywords: ["gema", "joya", "tesoro", "diamante"] },
  { name: "ghost", Icon: Ghost, keywords: ["fantasma", "misterio", "leyenda"] },
  { name: "puzzle", Icon: Puzzle, keywords: ["puzle", "pieza", "juego", "reto"] },
  { name: "dice-5", Icon: Dice5, keywords: ["dado", "juego", "azar"] },
];
