/**
 * Referencia OpenAPI 3.1 de la API de ULL360 (§5.6). Resumen navegable de
 * todas las rutas; el detalle de cada esquema vive en los validadores zod.
 */
export function openApiSpec(publicUrl: string): Record<string, unknown> {
  const p = (summary: string, tag: string, extra: Record<string, unknown> = {}): Record<string, unknown> => ({
    summary,
    tags: [tag],
    responses: { "200": { description: "OK" }, "4XX": { $ref: "#/components/responses/Problem" } },
    ...extra,
  });
  return {
    openapi: "3.1.0",
    info: {
      title: "ULL360 API",
      version: "1.0.0",
      description:
        "API REST de ULL360. Autenticacion por sesion (cookie) o token personal `Authorization: Bearer ull360_...` con scopes. Errores en formato RFC 9457 (application/problem+json). Mutaciones con sesion requieren cabecera X-CSRF-Token (doble token).",
      license: { name: "EUPL-1.2", url: "https://joinup.ec.europa.eu/collection/eupl" },
    },
    servers: [{ url: `${publicUrl}/api/v1` }],
    tags: [
      { name: "auth" }, { name: "orgs" }, { name: "projects" }, { name: "content" },
      { name: "media" }, { name: "translations" }, { name: "comments" }, { name: "publish" },
      { name: "analytics" }, { name: "forms" }, { name: "lti" }, { name: "admin" },
      { name: "tokens" }, { name: "live" }, { name: "public" },
    ],
    paths: {
      "/auth/register": { post: p("Registro de usuario (crea organizacion inicial)", "auth") },
      "/auth/login": { post: p("Inicio de sesion (email+contrasena, TOTP opcional)", "auth") },
      "/auth/logout": { post: p("Cerrar sesion", "auth") },
      "/auth/verify": { get: p("Verificacion de email", "auth") },
      "/auth/password/forgot": { post: p("Solicitar restablecimiento", "auth") },
      "/auth/password/reset": { post: p("Restablecer contrasena", "auth") },
      "/auth/oidc/start": { get: p("Inicio SSO OIDC institucional", "auth") },
      "/auth/oidc/callback": { get: p("Callback OIDC (alta JIT por dominio)", "auth") },
      "/auth/totp/setup": { post: p("Generar secreto TOTP", "auth") },
      "/auth/totp/confirm": { post: p("Activar 2FA TOTP", "auth") },
      "/auth/totp/disable": { post: p("Desactivar 2FA", "auth") },
      "/me": { get: p("Perfil y organizaciones del usuario", "auth") },
      "/orgs": { post: p("Crear organizacion", "orgs") },
      "/orgs/{orgId}": { get: p("Detalle", "orgs"), patch: p("Actualizar", "orgs") },
      "/orgs/{orgId}/usage": { get: p("Uso de cuotas (almacenamiento y tours)", "orgs") },
      "/orgs/{orgId}/members": { get: p("Miembros e invitaciones", "orgs"), post: p("Anadir miembro o invitar por email", "orgs") },
      "/orgs/{orgId}/members/{userId}": { patch: p("Cambiar rol", "orgs"), delete: p("Eliminar miembro", "orgs") },
      "/orgs/invites/accept": { post: p("Aceptar invitacion", "orgs") },
      "/projects": { get: p("Listar proyectos (carpetas, etiquetas, papelera)", "projects"), post: p("Crear proyecto (opcionalmente desde plantilla)", "projects") },
      "/projects/{id}": { get: p("Detalle con permisos y publicacion", "projects"), patch: p("Actualizar (titulo, carpeta, etiquetas, ajustes de tour)", "projects"), delete: p("Enviar a la papelera (retencion 30 dias)", "projects") },
      "/projects/{id}/restore": { post: p("Restaurar de la papelera", "projects") },
      "/projects/{id}/permanent": { delete: p("Borrado definitivo", "projects") },
      "/projects/{id}/duplicate": { post: p("Duplicar tour", "projects") },
      "/projects/{id}/members": { get: p("Comparticion", "projects"), post: p("Compartir con usuario", "projects") },
      "/projects/{id}/scenes": { get: p("Escenas + hotspots + conexiones del borrador", "content"), post: p("Crear escena", "content") },
      "/projects/{id}/scenes/{sceneId}": { patch: p("Editar escena", "content"), delete: p("Eliminar escena", "content") },
      "/projects/{id}/scenes/reorder": { post: p("Reordenar escenas", "content") },
      "/projects/{id}/scenes/{sceneId}/hotspots": { post: p("Crear hotspot (17 tipos)", "content") },
      "/projects/{id}/hotspots/{hotspotId}": { patch: p("Editar hotspot", "content"), delete: p("Eliminar hotspot", "content") },
      "/projects/{id}/connections": { post: p("Crear conexion del grafo", "content") },
      "/projects/{id}/connections/{connectionId}": { patch: p("Editar conexion", "content"), delete: p("Eliminar conexion", "content") },
      "/projects/{id}/translations/{lang}": { get: p("Traducciones de un idioma", "translations"), put: p("Guardar traducciones", "translations") },
      "/projects/{id}/translations/{lang}/xliff": { get: p("Export XLIFF 1.2", "translations"), post: p("Import XLIFF", "translations") },
      "/projects/{id}/translations/{lang}/csv": { get: p("Export CSV", "translations"), post: p("Import CSV", "translations") },
      "/projects/{id}/comments": { get: p("Comentarios con hilos", "comments"), post: p("Crear comentario anclado", "comments") },
      "/projects/{id}/comments/{commentId}": { patch: p("Editar/resolver", "comments"), delete: p("Eliminar", "comments") },
      "/projects/{id}/compile": { post: p("Compilar borrador a tour.json de previsualizacion", "publish") },
      "/projects/{id}/publish": { post: p("Publicar (congela version inmutable en /t/{slug})", "publish") },
      "/projects/{id}/unpublish": { post: p("Despublicar", "publish") },
      "/projects/{id}/versions": { get: p("Historial de versiones", "publish"), post: p("Instantanea manual con nombre", "publish") },
      "/projects/{id}/versions/{n}/tour": { get: p("tour.json de una version (diff)", "publish") },
      "/projects/{id}/versions/{n}/restore": { post: p("Republicar version anterior", "publish") },
      "/projects/{id}/export": { post: p("Parametros de export: tour compilado + lista de assets (el ZIP se arma en el navegador)", "publish") },
      "/projects/{id}/export.ull360": { get: p("Exportar proyecto portable .ull360", "publish") },
      "/projects/import.ull360": { post: p("Importar proyecto .ull360", "publish") },
      "/projects/{id}/analytics": { get: p("Analitica agregada (embudo, hotspots, heatmap de orientaciones)", "analytics") },
      "/projects/{id}/submissions.csv": { get: p("Export CSV de formularios", "forms") },
      "/projects/{id}/quiz-results.csv": { get: p("Export CSV de resultados de quiz", "forms") },
      "/media": { get: p("Biblioteca de medios (filtros, busqueda)", "media"), post: p("Iniciar subida (URLs prefirmadas multiparte; dedup por sha256)", "media") },
      "/media/{id}/parts": { post: p("URLs de partes multiparte", "media") },
      "/media/{id}/complete-multipart": { post: p("Completar multiparte", "media") },
      "/media/{id}/complete": { post: p("Confirmar subida (validacion magic bytes, saneado SVG)", "media") },
      "/media/{id}/derivatives": { post: p("Registrar manifiesto de tiles/derivados (validado)", "media") },
      "/media/{id}/derivative-uploads": { post: p("URLs prefirmadas para lotes de tiles", "media") },
      "/media/{id}/process": { post: p("Encolar procesado en servidor (contenedor)", "media") },
      "/media/{id}": { delete: p("Eliminar medio", "media") },
      "/lti/login": { post: p("OIDC login initiation (LTI 1.3)", "lti") },
      "/lti/launch": { post: p("Launch: ResourceLink o DeepLinkingRequest", "lti") },
      "/lti/deeplink": { post: p("Respuesta Deep Linking firmada", "lti") },
      "/lti/jwks": { get: p("JWKS de la herramienta", "lti") },
      "/lti/registrations": { get: p("Registros de plataformas", "lti"), post: p("Registrar plataforma (Moodle)", "lti") },
      "/live/rooms": { post: p("Crear sala de visita guiada (codigo efimero + clave de guia)", "live") },
      "/tokens": { get: p("Tokens personales", "tokens"), post: p("Crear token con scopes", "tokens") },
      "/admin/overview": { get: p("Resumen de instancia", "admin") },
      "/admin/settings": { get: p("Ajustes de instancia", "admin"), put: p("Guardar ajustes", "admin") },
      "/admin/users": { get: p("Usuarios", "admin") },
      "/admin/orgs": { get: p("Organizaciones y cuotas", "admin") },
      "/admin/jobs": { get: p("Cola de trabajos", "admin") },
      "/admin/audit": { get: p("Registro de auditoria", "admin") },
      "/admin/webhooks": { get: p("Webhooks", "admin"), post: p("Crear webhook", "admin") },
      "/admin/backup": { get: p("Export completo de instancia", "admin") },
      "/admin/backup/import": { post: p("Import de instancia", "admin") },
      "/public/forms/{slug}": { post: p("Envio publico de formulario (Turnstile)", "public") },
      "/public/quiz/{slug}": { post: p("Resultado publico de quiz (con passback LTI AGS)", "public") },
    },
    components: {
      responses: {
        Problem: {
          description: "Error RFC 9457",
          content: { "application/problem+json": { schema: { type: "object", properties: { type: { type: "string" }, title: { type: "string" }, status: { type: "integer" }, detail: { type: "string" } } } } },
        },
      },
      securitySchemes: {
        session: { type: "apiKey", in: "cookie", name: "u3s" },
        token: { type: "http", scheme: "bearer", description: "Token personal ull360_* con scopes" },
      },
    },
  };
}
